execute as @a if score @s xp matches 0.. run scoreboard players set @s levels 1
execute as @a if score @s xp matches 25.. run scoreboard players set @s levels 2
execute as @a if score @s xp matches 100.. run scoreboard players set @s levels 3
execute as @a if score @s xp matches 225.. run scoreboard players set @s levels 4
execute as @a if score @s xp matches 400.. run scoreboard players set @s levels 5
execute as @a if score @s xp matches 625.. run scoreboard players set @s levels 6
execute as @a if score @s xp matches 900.. run scoreboard players set @s levels 7
execute as @a if score @s xp matches 1225.. run scoreboard players set @s levels 8
execute as @a if score @s xp matches 1600.. run scoreboard players set @s levels 9
execute as @a if score @s xp matches 2025.. run scoreboard players set @s levels 10
execute as @a if score @s xp matches 2500.. run scoreboard players set @s levels 11
execute as @a if score @s xp matches 3025.. run scoreboard players set @s levels 12
execute as @a if score @s xp matches 3600.. run scoreboard players set @s levels 13
execute as @a if score @s xp matches 4225.. run scoreboard players set @s levels 14
execute as @a if score @s xp matches 4900.. run scoreboard players set @s levels 15
execute as @a if score @s xp matches 5625.. run scoreboard players set @s levels 16
execute as @a if score @s xp matches 6400.. run scoreboard players set @s levels 17
execute as @a if score @s xp matches 7225.. run scoreboard players set @s levels 18
execute as @a if score @s xp matches 8100.. run scoreboard players set @s levels 19
execute as @a if score @s xp matches 9025.. run scoreboard players set @s levels 20
execute as @a if score @s xp matches 10000.. run scoreboard players set @s levels 21
execute as @a if score @s xp matches 11025.. run scoreboard players set @s levels 22
execute as @a if score @s xp matches 12100.. run scoreboard players set @s levels 23
execute as @a if score @s xp matches 13225.. run scoreboard players set @s levels 24
execute as @a if score @s xp matches 14400.. run scoreboard players set @s levels 25
execute as @a if score @s xp matches 15625.. run scoreboard players set @s levels 26
execute as @a if score @s xp matches 16900.. run scoreboard players set @s levels 27
execute as @a if score @s xp matches 18225.. run scoreboard players set @s levels 28
execute as @a if score @s xp matches 19600.. run scoreboard players set @s levels 29
execute as @a if score @s xp matches 21025.. run scoreboard players set @s levels 30
execute as @a if score @s xp matches 22500.. run scoreboard players set @s levels 31
execute as @a if score @s xp matches 24025.. run scoreboard players set @s levels 32
execute as @a if score @s xp matches 25600.. run scoreboard players set @s levels 33
execute as @a if score @s xp matches 27225.. run scoreboard players set @s levels 34
execute as @a if score @s xp matches 28900.. run scoreboard players set @s levels 35
execute as @a if score @s xp matches 30625.. run scoreboard players set @s levels 36
execute as @a if score @s xp matches 32400.. run scoreboard players set @s levels 37
execute as @a if score @s xp matches 34225.. run scoreboard players set @s levels 38
execute as @a if score @s xp matches 36100.. run scoreboard players set @s levels 39
execute as @a if score @s xp matches 38025.. run scoreboard players set @s levels 40
execute as @a if score @s xp matches 40000.. run scoreboard players set @s levels 41
execute as @a if score @s xp matches 42025.. run scoreboard players set @s levels 42
execute as @a if score @s xp matches 44100.. run scoreboard players set @s levels 43
execute as @a if score @s xp matches 46225.. run scoreboard players set @s levels 44
execute as @a if score @s xp matches 48400.. run scoreboard players set @s levels 45
execute as @a if score @s xp matches 50625.. run scoreboard players set @s levels 46
execute as @a if score @s xp matches 52900.. run scoreboard players set @s levels 47
execute as @a if score @s xp matches 55225.. run scoreboard players set @s levels 48
execute as @a if score @s xp matches 57600.. run scoreboard players set @s levels 49
execute as @a if score @s xp matches 60025.. run scoreboard players set @s levels 50
execute as @a if score @s xp matches 62500.. run scoreboard players set @s levels 51
execute as @a if score @s xp matches 65025.. run scoreboard players set @s levels 52
execute as @a if score @s xp matches 67600.. run scoreboard players set @s levels 53
execute as @a if score @s xp matches 70225.. run scoreboard players set @s levels 54
execute as @a if score @s xp matches 72900.. run scoreboard players set @s levels 55
execute as @a if score @s xp matches 75625.. run scoreboard players set @s levels 56
execute as @a if score @s xp matches 78400.. run scoreboard players set @s levels 57
execute as @a if score @s xp matches 81225.. run scoreboard players set @s levels 58
execute as @a if score @s xp matches 84100.. run scoreboard players set @s levels 59
execute as @a if score @s xp matches 87025.. run scoreboard players set @s levels 60
execute as @a if score @s xp matches 90000.. run scoreboard players set @s levels 61
execute as @a if score @s xp matches 93025.. run scoreboard players set @s levels 62
execute as @a if score @s xp matches 96100.. run scoreboard players set @s levels 63
execute as @a if score @s xp matches 99225.. run scoreboard players set @s levels 64
execute as @a if score @s xp matches 102400.. run scoreboard players set @s levels 65
execute as @a if score @s xp matches 105625.. run scoreboard players set @s levels 66
execute as @a if score @s xp matches 108900.. run scoreboard players set @s levels 67
execute as @a if score @s xp matches 112225.. run scoreboard players set @s levels 68
execute as @a if score @s xp matches 115600.. run scoreboard players set @s levels 69
execute as @a if score @s xp matches 119025.. run scoreboard players set @s levels 70
execute as @a if score @s xp matches 122500.. run scoreboard players set @s levels 71
execute as @a if score @s xp matches 126025.. run scoreboard players set @s levels 72
execute as @a if score @s xp matches 129600.. run scoreboard players set @s levels 73
execute as @a if score @s xp matches 133225.. run scoreboard players set @s levels 74
execute as @a if score @s xp matches 136900.. run scoreboard players set @s levels 75
execute as @a if score @s xp matches 140625.. run scoreboard players set @s levels 76
execute as @a if score @s xp matches 144400.. run scoreboard players set @s levels 77
execute as @a if score @s xp matches 148225.. run scoreboard players set @s levels 78
execute as @a if score @s xp matches 152100.. run scoreboard players set @s levels 79
execute as @a if score @s xp matches 156025.. run scoreboard players set @s levels 80
execute as @a if score @s xp matches 160000.. run scoreboard players set @s levels 81
execute as @a if score @s xp matches 164025.. run scoreboard players set @s levels 82
execute as @a if score @s xp matches 168100.. run scoreboard players set @s levels 83
execute as @a if score @s xp matches 172225.. run scoreboard players set @s levels 84
execute as @a if score @s xp matches 176400.. run scoreboard players set @s levels 85
execute as @a if score @s xp matches 180625.. run scoreboard players set @s levels 86
execute as @a if score @s xp matches 184900.. run scoreboard players set @s levels 87
execute as @a if score @s xp matches 189225.. run scoreboard players set @s levels 88
execute as @a if score @s xp matches 193600.. run scoreboard players set @s levels 89
execute as @a if score @s xp matches 198025.. run scoreboard players set @s levels 90
execute as @a if score @s xp matches 202500.. run scoreboard players set @s levels 91
execute as @a if score @s xp matches 207025.. run scoreboard players set @s levels 92
execute as @a if score @s xp matches 211600.. run scoreboard players set @s levels 93
execute as @a if score @s xp matches 216225.. run scoreboard players set @s levels 94
execute as @a if score @s xp matches 220900.. run scoreboard players set @s levels 95
execute as @a if score @s xp matches 225625.. run scoreboard players set @s levels 96
execute as @a if score @s xp matches 230400.. run scoreboard players set @s levels 97
execute as @a if score @s xp matches 235225.. run scoreboard players set @s levels 98
execute as @a if score @s xp matches 240100.. run scoreboard players set @s levels 99
execute as @a if score @s xp matches 245025.. run scoreboard players set @s levels 100
execute as @a if score @s xp matches 250000.. run scoreboard players set @s levels 101
execute as @a if score @s xp matches 255025.. run scoreboard players set @s levels 102
execute as @a if score @s xp matches 260100.. run scoreboard players set @s levels 103
execute as @a if score @s xp matches 265225.. run scoreboard players set @s levels 104
execute as @a if score @s xp matches 270400.. run scoreboard players set @s levels 105
execute as @a if score @s xp matches 275625.. run scoreboard players set @s levels 106
execute as @a if score @s xp matches 280900.. run scoreboard players set @s levels 107
execute as @a if score @s xp matches 286225.. run scoreboard players set @s levels 108
execute as @a if score @s xp matches 291600.. run scoreboard players set @s levels 109
execute as @a if score @s xp matches 297025.. run scoreboard players set @s levels 110
execute as @a if score @s xp matches 302500.. run scoreboard players set @s levels 111
execute as @a if score @s xp matches 308025.. run scoreboard players set @s levels 112
execute as @a if score @s xp matches 313600.. run scoreboard players set @s levels 113
execute as @a if score @s xp matches 319225.. run scoreboard players set @s levels 114
execute as @a if score @s xp matches 324900.. run scoreboard players set @s levels 115
execute as @a if score @s xp matches 330625.. run scoreboard players set @s levels 116
execute as @a if score @s xp matches 336400.. run scoreboard players set @s levels 117
execute as @a if score @s xp matches 342225.. run scoreboard players set @s levels 118
execute as @a if score @s xp matches 348100.. run scoreboard players set @s levels 119
execute as @a if score @s xp matches 354025.. run scoreboard players set @s levels 120
execute as @a if score @s xp matches 360000.. run scoreboard players set @s levels 121
execute as @a if score @s xp matches 366025.. run scoreboard players set @s levels 122
execute as @a if score @s xp matches 372100.. run scoreboard players set @s levels 123
execute as @a if score @s xp matches 378225.. run scoreboard players set @s levels 124
execute as @a if score @s xp matches 384400.. run scoreboard players set @s levels 125
execute as @a if score @s xp matches 390625.. run scoreboard players set @s levels 126
execute as @a if score @s xp matches 396900.. run scoreboard players set @s levels 127
execute as @a if score @s xp matches 403225.. run scoreboard players set @s levels 128
execute as @a if score @s xp matches 409600.. run scoreboard players set @s levels 129
execute as @a if score @s xp matches 416025.. run scoreboard players set @s levels 130
execute as @a if score @s xp matches 422500.. run scoreboard players set @s levels 131
execute as @a if score @s xp matches 429025.. run scoreboard players set @s levels 132
execute as @a if score @s xp matches 435600.. run scoreboard players set @s levels 133
execute as @a if score @s xp matches 442225.. run scoreboard players set @s levels 134
execute as @a if score @s xp matches 448900.. run scoreboard players set @s levels 135
execute as @a if score @s xp matches 455625.. run scoreboard players set @s levels 136
execute as @a if score @s xp matches 462400.. run scoreboard players set @s levels 137
execute as @a if score @s xp matches 469225.. run scoreboard players set @s levels 138
execute as @a if score @s xp matches 476100.. run scoreboard players set @s levels 139
execute as @a if score @s xp matches 483025.. run scoreboard players set @s levels 140
execute as @a if score @s xp matches 490000.. run scoreboard players set @s levels 141
execute as @a if score @s xp matches 497025.. run scoreboard players set @s levels 142
execute as @a if score @s xp matches 504100.. run scoreboard players set @s levels 143
execute as @a if score @s xp matches 511225.. run scoreboard players set @s levels 144
execute as @a if score @s xp matches 518400.. run scoreboard players set @s levels 145
execute as @a if score @s xp matches 525625.. run scoreboard players set @s levels 146
execute as @a if score @s xp matches 532900.. run scoreboard players set @s levels 147
execute as @a if score @s xp matches 540225.. run scoreboard players set @s levels 148
execute as @a if score @s xp matches 547600.. run scoreboard players set @s levels 149
execute as @a if score @s xp matches 555025.. run scoreboard players set @s levels 150
execute as @a if score @s xp matches 562500.. run scoreboard players set @s levels 151
execute as @a if score @s xp matches 570025.. run scoreboard players set @s levels 152
execute as @a if score @s xp matches 577600.. run scoreboard players set @s levels 153
execute as @a if score @s xp matches 585225.. run scoreboard players set @s levels 154
execute as @a if score @s xp matches 592900.. run scoreboard players set @s levels 155
execute as @a if score @s xp matches 600625.. run scoreboard players set @s levels 156
execute as @a if score @s xp matches 608400.. run scoreboard players set @s levels 157
execute as @a if score @s xp matches 616225.. run scoreboard players set @s levels 158
execute as @a if score @s xp matches 624100.. run scoreboard players set @s levels 159
execute as @a if score @s xp matches 632025.. run scoreboard players set @s levels 160
execute as @a if score @s xp matches 640000.. run scoreboard players set @s levels 161
execute as @a if score @s xp matches 648025.. run scoreboard players set @s levels 162
execute as @a if score @s xp matches 656100.. run scoreboard players set @s levels 163
execute as @a if score @s xp matches 664225.. run scoreboard players set @s levels 164
execute as @a if score @s xp matches 672400.. run scoreboard players set @s levels 165
execute as @a if score @s xp matches 680625.. run scoreboard players set @s levels 166
execute as @a if score @s xp matches 688900.. run scoreboard players set @s levels 167
execute as @a if score @s xp matches 697225.. run scoreboard players set @s levels 168
execute as @a if score @s xp matches 705600.. run scoreboard players set @s levels 169
execute as @a if score @s xp matches 714025.. run scoreboard players set @s levels 170
execute as @a if score @s xp matches 722500.. run scoreboard players set @s levels 171
execute as @a if score @s xp matches 731025.. run scoreboard players set @s levels 172
execute as @a if score @s xp matches 739600.. run scoreboard players set @s levels 173
execute as @a if score @s xp matches 748225.. run scoreboard players set @s levels 174
execute as @a if score @s xp matches 756900.. run scoreboard players set @s levels 175
execute as @a if score @s xp matches 765625.. run scoreboard players set @s levels 176
execute as @a if score @s xp matches 774400.. run scoreboard players set @s levels 177
execute as @a if score @s xp matches 783225.. run scoreboard players set @s levels 178
execute as @a if score @s xp matches 792100.. run scoreboard players set @s levels 179
execute as @a if score @s xp matches 801025.. run scoreboard players set @s levels 180
execute as @a if score @s xp matches 810000.. run scoreboard players set @s levels 181
execute as @a if score @s xp matches 819025.. run scoreboard players set @s levels 182
execute as @a if score @s xp matches 828100.. run scoreboard players set @s levels 183
execute as @a if score @s xp matches 837225.. run scoreboard players set @s levels 184
execute as @a if score @s xp matches 846400.. run scoreboard players set @s levels 185
execute as @a if score @s xp matches 855625.. run scoreboard players set @s levels 186
execute as @a if score @s xp matches 864900.. run scoreboard players set @s levels 187
execute as @a if score @s xp matches 874225.. run scoreboard players set @s levels 188
execute as @a if score @s xp matches 883600.. run scoreboard players set @s levels 189
execute as @a if score @s xp matches 893025.. run scoreboard players set @s levels 190
execute as @a if score @s xp matches 902500.. run scoreboard players set @s levels 191
execute as @a if score @s xp matches 912025.. run scoreboard players set @s levels 192
execute as @a if score @s xp matches 921600.. run scoreboard players set @s levels 193
execute as @a if score @s xp matches 931225.. run scoreboard players set @s levels 194
execute as @a if score @s xp matches 940900.. run scoreboard players set @s levels 195
execute as @a if score @s xp matches 950625.. run scoreboard players set @s levels 196
execute as @a if score @s xp matches 960400.. run scoreboard players set @s levels 197
execute as @a if score @s xp matches 970225.. run scoreboard players set @s levels 198
execute as @a if score @s xp matches 980100.. run scoreboard players set @s levels 199
execute as @a if score @s xp matches 990025.. run scoreboard players set @s levels 200
execute as @a if score @s xp matches 1000000.. run scoreboard players set @s levels 201
execute as @a if score @s xp matches 1010025.. run scoreboard players set @s levels 202
execute as @a if score @s xp matches 1020100.. run scoreboard players set @s levels 203
execute as @a if score @s xp matches 1030225.. run scoreboard players set @s levels 204
execute as @a if score @s xp matches 1040400.. run scoreboard players set @s levels 205
execute as @a if score @s xp matches 1050625.. run scoreboard players set @s levels 206
execute as @a if score @s xp matches 1060900.. run scoreboard players set @s levels 207
execute as @a if score @s xp matches 1071225.. run scoreboard players set @s levels 208
execute as @a if score @s xp matches 1081600.. run scoreboard players set @s levels 209
execute as @a if score @s xp matches 1092025.. run scoreboard players set @s levels 210
execute as @a if score @s xp matches 1102500.. run scoreboard players set @s levels 211
execute as @a if score @s xp matches 1113025.. run scoreboard players set @s levels 212
execute as @a if score @s xp matches 1123600.. run scoreboard players set @s levels 213
execute as @a if score @s xp matches 1134225.. run scoreboard players set @s levels 214
execute as @a if score @s xp matches 1144900.. run scoreboard players set @s levels 215
execute as @a if score @s xp matches 1155625.. run scoreboard players set @s levels 216
execute as @a if score @s xp matches 1166400.. run scoreboard players set @s levels 217
execute as @a if score @s xp matches 1177225.. run scoreboard players set @s levels 218
execute as @a if score @s xp matches 1188100.. run scoreboard players set @s levels 219
execute as @a if score @s xp matches 1199025.. run scoreboard players set @s levels 220
execute as @a if score @s xp matches 1210000.. run scoreboard players set @s levels 221
execute as @a if score @s xp matches 1221025.. run scoreboard players set @s levels 222
execute as @a if score @s xp matches 1232100.. run scoreboard players set @s levels 223
execute as @a if score @s xp matches 1243225.. run scoreboard players set @s levels 224
execute as @a if score @s xp matches 1254400.. run scoreboard players set @s levels 225
execute as @a if score @s xp matches 1265625.. run scoreboard players set @s levels 226
execute as @a if score @s xp matches 1276900.. run scoreboard players set @s levels 227
execute as @a if score @s xp matches 1288225.. run scoreboard players set @s levels 228
execute as @a if score @s xp matches 1299600.. run scoreboard players set @s levels 229
execute as @a if score @s xp matches 1311025.. run scoreboard players set @s levels 230
execute as @a if score @s xp matches 1322500.. run scoreboard players set @s levels 231
execute as @a if score @s xp matches 1334025.. run scoreboard players set @s levels 232
execute as @a if score @s xp matches 1345600.. run scoreboard players set @s levels 233
execute as @a if score @s xp matches 1357225.. run scoreboard players set @s levels 234
execute as @a if score @s xp matches 1368900.. run scoreboard players set @s levels 235
execute as @a if score @s xp matches 1380625.. run scoreboard players set @s levels 236
execute as @a if score @s xp matches 1392400.. run scoreboard players set @s levels 237
execute as @a if score @s xp matches 1404225.. run scoreboard players set @s levels 238
execute as @a if score @s xp matches 1416100.. run scoreboard players set @s levels 239
execute as @a if score @s xp matches 1428025.. run scoreboard players set @s levels 240
execute as @a if score @s xp matches 1440000.. run scoreboard players set @s levels 241
execute as @a if score @s xp matches 1452025.. run scoreboard players set @s levels 242
execute as @a if score @s xp matches 1464100.. run scoreboard players set @s levels 243
execute as @a if score @s xp matches 1476225.. run scoreboard players set @s levels 244
execute as @a if score @s xp matches 1488400.. run scoreboard players set @s levels 245
execute as @a if score @s xp matches 1500625.. run scoreboard players set @s levels 246
execute as @a if score @s xp matches 1512900.. run scoreboard players set @s levels 247
execute as @a if score @s xp matches 1525225.. run scoreboard players set @s levels 248
execute as @a if score @s xp matches 1537600.. run scoreboard players set @s levels 249
execute as @a if score @s xp matches 1550025.. run scoreboard players set @s levels 250
