kill @e[type=item,name="Coal "]
kill @e[type=item,name="Ancient Debris "]
kill @e[type=item,name="Copper Ingot "]
kill @e[type=item,name="Diamond "]
kill @e[type=item,name="Emerald "]
kill @e[type=item,name="End Stone "]
kill @e[type=item,name="Gold Ingot "]
kill @e[type=item,name="Iron Ingot "]
kill @e[type=item,name="Lapis Lazuli "]
kill @e[type=item,name="Netherrack "]
kill @e[type=item,name="Obsidian "]
kill @e[type=item,name="Quartz "]
kill @e[type=item,name="Redstone "]
