function levels/xp
function mines/mines
function shop/shop
function misc/gamerules
function misc/scores
function misc/koth
function misc/elevation
function levels/levels
function misc/koth
function fragments/fragments
function beacons/beacon
function timer
function custom_crafting/cc
function custom_crafting/stats
function scoreboardadd
function tellraw
function tempac
function gems/gem_shop