execute as @a[hasitem={item=radiant:wood_pickaxe}] if score @s money matches 0.. run give @s wooden_pickaxe 1 0 {"minecraft:can_destroy":{"blocks":["coal_ore","copper_ore","iron_ore","gold_ore","lapis_ore","redstone_ore","lit_redstone_ore","diamond_ore","netherrack","quartz_ore","ancient_debris","emerald_ore","end_stone","obsidian","iron_block","gold_block","lapis_block","redstone_block","diamond_block","emerald_block","netherite_block"]}}
execute as @a[hasitem={item=radiant:wood_pickaxe}] run clear @s radiant:wood_pickaxe
execute as @a[hasitem={item=radiant:stone_pickaxe}] if score @s money matches 100.. run give @s stone_pickaxe 1 0 {"minecraft:can_destroy":{"blocks":["coal_ore","copper_ore","iron_ore","gold_ore","lapis_ore","redstone_ore","lit_redstone_ore","diamond_ore","netherrack","quartz_ore","ancient_debris","emerald_ore","end_stone","obsidian","iron_block","gold_block","lapis_block","redstone_block","diamond_block","emerald_block","netherite_block"]}}
execute as @a[hasitem={item=radiant:stone_pickaxe}] run clear @s radiant:stone_pickaxe
execute as @a[hasitem={item=radiant:iron_pickaxe}] if score @s money matches 25000.. run give @s iron_pickaxe 1 0 {"minecraft:can_destroy":{"blocks":["coal_ore","copper_ore","iron_ore","gold_ore","lapis_ore","redstone_ore","lit_redstone_ore","diamond_ore","netherrack","quartz_ore","ancient_debris","emerald_ore","end_stone","obsidian","iron_block","gold_block","lapis_block","redstone_block","diamond_block","emerald_block","netherite_block"]}}
execute as @a[hasitem={item=radiant:iron_pickaxe}] run clear @s radiant:iron_pickaxe
execute as @a[hasitem={item=radiant:diamond_pickaxe}] if score @s money matches 250000.. if score @s prestige matches 1.. run give @s diamond_pickaxe 1 0 {"minecraft:can_destroy":{"blocks":["coal_ore","copper_ore","iron_ore","gold_ore","lapis_ore","redstone_ore","lit_redstone_ore","diamond_ore","netherrack","quartz_ore","ancient_debris","emerald_ore","end_stone","obsidian","iron_block","gold_block","lapis_block","redstone_block","diamond_block","emerald_block","netherite_block"]}}
execute as @a[hasitem={item=radiant:diamond_pickaxe}] run clear @s radiant:diamond_pickaxe
execute as @a[hasitem={item=radiant:netherite_pickaxe}] if score @s money matches 5000000.. if score @s prestige matches 5.. run give @s netherite_pickaxe 1 0 {"minecraft:can_destroy":{"blocks":["coal_ore","copper_ore","iron_ore","gold_ore","lapis_ore","redstone_ore","lit_redstone_ore","diamond_ore","netherrack","quartz_ore","ancient_debris","emerald_ore","end_stone","obsidian","iron_block","gold_block","lapis_block","redstone_block","diamond_block","emerald_block","netherite_block"]}}
execute as @a[hasitem={item=radiant:netherite_pickaxe}] run clear @s radiant:netherite_pickaxe