kill @e[type=item,name="Chainmail Armor(200$)"]
kill @e[type=item,name="Common Crate(450$)"]
kill @e[type=item,name="Diamond Armor(250000$)"]
kill @e[type=item,name="Diamond Pickaxe (250000$ Prestige 1)"]
kill @e[type=item,name="Diamond Sword (25000$)"]
kill @e[type=item,name=" "]
kill @e[type=item,name="Gold Armor(200$)"]
kill @e[type=item,name="Iron Armor (25000$)"]
kill @e[type=item,name="Iron Pickaxe (2500$)"]
kill @e[type=item,name="Iron Sword (5000$)"]
kill @e[type=item,name="Leather Armor(100$)"]
kill @e[type=item,name="Legendary Crate(900$)"]
kill @e[type=item,name="Netherite Armor(5000000$)"]
kill @e[type=item,name="Netherite Pickaxe (5M$ Prestige 5)"]
kill @e[type=item,name="Netherite Sword (125000$)"]
kill @e[type=item,name="Prestige (100k$ Max Level"]
kill @e[type=item,name="Prestige (100k$ Max Level"]
kill @e[type=item,name="Stone Sword (1000$)"]
kill @e[type=item,name="Wood Pickaxe (Free)"]
kill @e[type=item,name="Wooden Sword (200$)"]
kill @e[type=item,name="Deluxe Crate(2,000F"]
kill @e[type=item,name="Dire Crate(3,500F)"]
kill @e[type=item,name="Radiant Crate(8,500F)"]
kill @e[type=item,name="Super Crate(1,000F)"]
kill @e[type=item,name="Rare Crate(900$)"]
kill @e[type=item,name="King of the Hill"]
