kill @e[type=item,name="Mine J (Level 200+ Prestige 1)"]
kill @e[type=item,name="Mine A (Level 0+)"]
kill @e[type=item,name="Mine B (Level 25+)"]
kill @e[type=item,name="Mine R (Level 0+ Prestige 6)"]
kill @e[type=item,name="Mine G (Level 250+)"]
kill @e[type=item,name="Mine S (Level 0+ Prestige 8)"]
kill @e[type=item,name="Mine L (Level 50+ Prestige 2)"]
kill @e[type=item,name="Mine H (Level 150+ Prestige 2)"]
kill @e[type=item,name="Mine O (Level 125+ Prestige 3)"]
kill @e[type=item,name="Mine D (Level 100+)"]
kill @e[type=item,name="Mine N (Level 0+ Prestige 3)"]
kill @e[type=item,name="Mine C (Level 50+)"]
kill @e[type=item,name="Mine P (Level 0+ Prestige 4)"]
kill @e[type=item,name="Mine E (Level 150+)"]
kill @e[type=item,name="Mine T (Level 0+ Prestige 10)"]
kill @e[type=item,name="Mine H (Level 50+ Prestige 1)"]
kill @e[type=item,name="Mine M (Level 200+ Prestige 2)"]
kill @e[type=item,name="Mine I (Level 150+ Prestige 1)"]
kill @e[type=item,name="Mine Q (Level 0+ Prestige 5)"]
kill @e[type=item,name="Mine F (Level 200+)"]