kill @e[type=item,name="Mine J (Level 200+ Prestige 1)"]
kill @e[type=item,name="Mine A (Level 0+)"]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]
kill @e[type=item,name=]