execute as @a if score @s fishingXp matches 252.. run scoreboard players set @s fishingLevel 1
execute as @a if score @s fishingXp matches 564.. run scoreboard players set @s fishingLevel 2
execute as @a if score @s fishingXp matches 977.. run scoreboard players set @s fishingLevel 3
execute as @a if score @s fishingXp matches 1537.. run scoreboard players set @s fishingLevel 4
execute as @a if score @s fishingXp matches 2311.. run scoreboard players set @s fishingLevel 5
execute as @a if score @s fishingXp matches 3400.. run scoreboard players set @s fishingLevel 6
execute as @a if score @s fishingXp matches 4958.. run scoreboard players set @s fishingLevel 7
execute as @a if score @s fishingXp matches 7218.. run scoreboard players set @s fishingLevel 8
execute as @a if score @s fishingXp matches 10548.. run scoreboard players set @s fishingLevel 9
execute as @a if score @s fishingXp matches 15530.. run scoreboard players set @s fishingLevel 10
execute as @a if score @s fishingXp matches 23096.. run scoreboard players set @s fishingLevel 11
execute as @a if score @s fishingXp matches 34772.. run scoreboard players set @s fishingLevel 12
execute as @a if score @s fishingXp matches 53079.. run scoreboard players set @s fishingLevel 13
execute as @a if score @s fishingXp matches 82271.. run scoreboard players set @s fishingLevel 14
execute as @a if score @s fishingXp matches 129627.. run scoreboard players set @s fishingLevel 15
execute as @a if score @s fishingXp matches 207839.. run scoreboard players set @s fishingLevel 16
execute as @a if score @s fishingXp matches 339435.. run scoreboard players set @s fishingLevel 17
execute as @a if score @s fishingXp matches 565171.. run scoreboard players set @s fishingLevel 18
execute as @a if score @s fishingXp matches 960241.. run scoreboard players set @s fishingLevel 19
execute as @a if score @s fishingXp matches 1666252.. run scoreboard players set @s fishingLevel 20