execute as @a if score @s xp matches 0.. run scoreboard players set @s levels 1
execute as @a if score @s xp matches 9.. run scoreboard players set @s levels 2
execute as @a if score @s xp matches 36.. run scoreboard players set @s levels 3
execute as @a if score @s xp matches 81.. run scoreboard players set @s levels 4
execute as @a if score @s xp matches 144.. run scoreboard players set @s levels 5
execute as @a if score @s xp matches 225.. run scoreboard players set @s levels 6
execute as @a if score @s xp matches 324.. run scoreboard players set @s levels 7
execute as @a if score @s xp matches 441.. run scoreboard players set @s levels 8
execute as @a if score @s xp matches 576.. run scoreboard players set @s levels 9
execute as @a if score @s xp matches 729.. run scoreboard players set @s levels 10
execute as @a if score @s xp matches 900.. run scoreboard players set @s levels 11
execute as @a if score @s xp matches 1089.. run scoreboard players set @s levels 12
execute as @a if score @s xp matches 1296.. run scoreboard players set @s levels 13
execute as @a if score @s xp matches 1521.. run scoreboard players set @s levels 14
execute as @a if score @s xp matches 1764.. run scoreboard players set @s levels 15
execute as @a if score @s xp matches 2025.. run scoreboard players set @s levels 16
execute as @a if score @s xp matches 2304.. run scoreboard players set @s levels 17
execute as @a if score @s xp matches 2601.. run scoreboard players set @s levels 18
execute as @a if score @s xp matches 2916.. run scoreboard players set @s levels 19
execute as @a if score @s xp matches 3249.. run scoreboard players set @s levels 20
execute as @a if score @s xp matches 3600.. run scoreboard players set @s levels 21
execute as @a if score @s xp matches 3969.. run scoreboard players set @s levels 22
execute as @a if score @s xp matches 4356.. run scoreboard players set @s levels 23
execute as @a if score @s xp matches 4761.. run scoreboard players set @s levels 24
execute as @a if score @s xp matches 5184.. run scoreboard players set @s levels 25
execute as @a if score @s xp matches 5625.. run scoreboard players set @s levels 26
execute as @a if score @s xp matches 6084.. run scoreboard players set @s levels 27
execute as @a if score @s xp matches 6561.. run scoreboard players set @s levels 28
execute as @a if score @s xp matches 7056.. run scoreboard players set @s levels 29
execute as @a if score @s xp matches 7569.. run scoreboard players set @s levels 30
execute as @a if score @s xp matches 8100.. run scoreboard players set @s levels 31
execute as @a if score @s xp matches 8649.. run scoreboard players set @s levels 32
execute as @a if score @s xp matches 9216.. run scoreboard players set @s levels 33
execute as @a if score @s xp matches 9801.. run scoreboard players set @s levels 34
execute as @a if score @s xp matches 10404.. run scoreboard players set @s levels 35
execute as @a if score @s xp matches 11025.. run scoreboard players set @s levels 36
execute as @a if score @s xp matches 11664.. run scoreboard players set @s levels 37
execute as @a if score @s xp matches 12321.. run scoreboard players set @s levels 38
execute as @a if score @s xp matches 12996.. run scoreboard players set @s levels 39
execute as @a if score @s xp matches 13689.. run scoreboard players set @s levels 40
execute as @a if score @s xp matches 14400.. run scoreboard players set @s levels 41
execute as @a if score @s xp matches 15129.. run scoreboard players set @s levels 42
execute as @a if score @s xp matches 15876.. run scoreboard players set @s levels 43
execute as @a if score @s xp matches 16641.. run scoreboard players set @s levels 44
execute as @a if score @s xp matches 17424.. run scoreboard players set @s levels 45
execute as @a if score @s xp matches 18225.. run scoreboard players set @s levels 46
execute as @a if score @s xp matches 19044.. run scoreboard players set @s levels 47
execute as @a if score @s xp matches 19881.. run scoreboard players set @s levels 48
execute as @a if score @s xp matches 20736.. run scoreboard players set @s levels 49
execute as @a if score @s xp matches 21609.. run scoreboard players set @s levels 50
execute as @a if score @s xp matches 22500.. run scoreboard players set @s levels 51
execute as @a if score @s xp matches 23409.. run scoreboard players set @s levels 52
execute as @a if score @s xp matches 24336.. run scoreboard players set @s levels 53
execute as @a if score @s xp matches 25281.. run scoreboard players set @s levels 54
execute as @a if score @s xp matches 26244.. run scoreboard players set @s levels 55
execute as @a if score @s xp matches 27225.. run scoreboard players set @s levels 56
execute as @a if score @s xp matches 28224.. run scoreboard players set @s levels 57
execute as @a if score @s xp matches 29241.. run scoreboard players set @s levels 58
execute as @a if score @s xp matches 30276.. run scoreboard players set @s levels 59
execute as @a if score @s xp matches 31329.. run scoreboard players set @s levels 60
execute as @a if score @s xp matches 32400.. run scoreboard players set @s levels 61
execute as @a if score @s xp matches 33489.. run scoreboard players set @s levels 62
execute as @a if score @s xp matches 34596.. run scoreboard players set @s levels 63
execute as @a if score @s xp matches 35721.. run scoreboard players set @s levels 64
execute as @a if score @s xp matches 36864.. run scoreboard players set @s levels 65
execute as @a if score @s xp matches 38025.. run scoreboard players set @s levels 66
execute as @a if score @s xp matches 39204.. run scoreboard players set @s levels 67
execute as @a if score @s xp matches 40401.. run scoreboard players set @s levels 68
execute as @a if score @s xp matches 41616.. run scoreboard players set @s levels 69
execute as @a if score @s xp matches 42849.. run scoreboard players set @s levels 70
execute as @a if score @s xp matches 44100.. run scoreboard players set @s levels 71
execute as @a if score @s xp matches 45369.. run scoreboard players set @s levels 72
execute as @a if score @s xp matches 46656.. run scoreboard players set @s levels 73
execute as @a if score @s xp matches 47961.. run scoreboard players set @s levels 74
execute as @a if score @s xp matches 49284.. run scoreboard players set @s levels 75
execute as @a if score @s xp matches 50625.. run scoreboard players set @s levels 76
execute as @a if score @s xp matches 51984.. run scoreboard players set @s levels 77
execute as @a if score @s xp matches 53361.. run scoreboard players set @s levels 78
execute as @a if score @s xp matches 54756.. run scoreboard players set @s levels 79
execute as @a if score @s xp matches 56169.. run scoreboard players set @s levels 80
execute as @a if score @s xp matches 57600.. run scoreboard players set @s levels 81
execute as @a if score @s xp matches 59049.. run scoreboard players set @s levels 82
execute as @a if score @s xp matches 60516.. run scoreboard players set @s levels 83
execute as @a if score @s xp matches 62001.. run scoreboard players set @s levels 84
execute as @a if score @s xp matches 63504.. run scoreboard players set @s levels 85
execute as @a if score @s xp matches 65025.. run scoreboard players set @s levels 86
execute as @a if score @s xp matches 66564.. run scoreboard players set @s levels 87
execute as @a if score @s xp matches 68121.. run scoreboard players set @s levels 88
execute as @a if score @s xp matches 69696.. run scoreboard players set @s levels 89
execute as @a if score @s xp matches 71289.. run scoreboard players set @s levels 90
execute as @a if score @s xp matches 72900.. run scoreboard players set @s levels 91
execute as @a if score @s xp matches 74529.. run scoreboard players set @s levels 92
execute as @a if score @s xp matches 76176.. run scoreboard players set @s levels 93
execute as @a if score @s xp matches 77841.. run scoreboard players set @s levels 94
execute as @a if score @s xp matches 79524.. run scoreboard players set @s levels 95
execute as @a if score @s xp matches 81225.. run scoreboard players set @s levels 96
execute as @a if score @s xp matches 82944.. run scoreboard players set @s levels 97
execute as @a if score @s xp matches 84681.. run scoreboard players set @s levels 98
execute as @a if score @s xp matches 86436.. run scoreboard players set @s levels 99
execute as @a if score @s xp matches 88209.. run scoreboard players set @s levels 100
execute as @a if score @s xp matches 90000.. run scoreboard players set @s levels 101
execute as @a if score @s xp matches 91809.. run scoreboard players set @s levels 102
execute as @a if score @s xp matches 93636.. run scoreboard players set @s levels 103
execute as @a if score @s xp matches 95481.. run scoreboard players set @s levels 104
execute as @a if score @s xp matches 97344.. run scoreboard players set @s levels 105
execute as @a if score @s xp matches 99225.. run scoreboard players set @s levels 106
execute as @a if score @s xp matches 101124.. run scoreboard players set @s levels 107
execute as @a if score @s xp matches 103041.. run scoreboard players set @s levels 108
execute as @a if score @s xp matches 104976.. run scoreboard players set @s levels 109
execute as @a if score @s xp matches 106929.. run scoreboard players set @s levels 110
execute as @a if score @s xp matches 108900.. run scoreboard players set @s levels 111
execute as @a if score @s xp matches 110889.. run scoreboard players set @s levels 112
execute as @a if score @s xp matches 112896.. run scoreboard players set @s levels 113
execute as @a if score @s xp matches 114921.. run scoreboard players set @s levels 114
execute as @a if score @s xp matches 116964.. run scoreboard players set @s levels 115
execute as @a if score @s xp matches 119025.. run scoreboard players set @s levels 116
execute as @a if score @s xp matches 121104.. run scoreboard players set @s levels 117
execute as @a if score @s xp matches 123201.. run scoreboard players set @s levels 118
execute as @a if score @s xp matches 125316.. run scoreboard players set @s levels 119
execute as @a if score @s xp matches 127449.. run scoreboard players set @s levels 120
execute as @a if score @s xp matches 129600.. run scoreboard players set @s levels 121
execute as @a if score @s xp matches 131769.. run scoreboard players set @s levels 122
execute as @a if score @s xp matches 133956.. run scoreboard players set @s levels 123
execute as @a if score @s xp matches 136161.. run scoreboard players set @s levels 124
execute as @a if score @s xp matches 138384.. run scoreboard players set @s levels 125
execute as @a if score @s xp matches 140625.. run scoreboard players set @s levels 126
execute as @a if score @s xp matches 142884.. run scoreboard players set @s levels 127
execute as @a if score @s xp matches 145161.. run scoreboard players set @s levels 128
execute as @a if score @s xp matches 147456.. run scoreboard players set @s levels 129
execute as @a if score @s xp matches 149769.. run scoreboard players set @s levels 130
execute as @a if score @s xp matches 152100.. run scoreboard players set @s levels 131
execute as @a if score @s xp matches 154449.. run scoreboard players set @s levels 132
execute as @a if score @s xp matches 156816.. run scoreboard players set @s levels 133
execute as @a if score @s xp matches 159201.. run scoreboard players set @s levels 134
execute as @a if score @s xp matches 161604.. run scoreboard players set @s levels 135
execute as @a if score @s xp matches 164025.. run scoreboard players set @s levels 136
execute as @a if score @s xp matches 166464.. run scoreboard players set @s levels 137
execute as @a if score @s xp matches 168921.. run scoreboard players set @s levels 138
execute as @a if score @s xp matches 171396.. run scoreboard players set @s levels 139
execute as @a if score @s xp matches 173889.. run scoreboard players set @s levels 140
execute as @a if score @s xp matches 176400.. run scoreboard players set @s levels 141
execute as @a if score @s xp matches 178929.. run scoreboard players set @s levels 142
execute as @a if score @s xp matches 181476.. run scoreboard players set @s levels 143
execute as @a if score @s xp matches 184041.. run scoreboard players set @s levels 144
execute as @a if score @s xp matches 186624.. run scoreboard players set @s levels 145
execute as @a if score @s xp matches 189225.. run scoreboard players set @s levels 146
execute as @a if score @s xp matches 191844.. run scoreboard players set @s levels 147
execute as @a if score @s xp matches 194481.. run scoreboard players set @s levels 148
execute as @a if score @s xp matches 197136.. run scoreboard players set @s levels 149
execute as @a if score @s xp matches 199809.. run scoreboard players set @s levels 150
execute as @a if score @s xp matches 202500.. run scoreboard players set @s levels 151
execute as @a if score @s xp matches 205209.. run scoreboard players set @s levels 152
execute as @a if score @s xp matches 207936.. run scoreboard players set @s levels 153
execute as @a if score @s xp matches 210681.. run scoreboard players set @s levels 154
execute as @a if score @s xp matches 213444.. run scoreboard players set @s levels 155
execute as @a if score @s xp matches 216225.. run scoreboard players set @s levels 156
execute as @a if score @s xp matches 219024.. run scoreboard players set @s levels 157
execute as @a if score @s xp matches 221841.. run scoreboard players set @s levels 158
execute as @a if score @s xp matches 224676.. run scoreboard players set @s levels 159
execute as @a if score @s xp matches 227529.. run scoreboard players set @s levels 160
execute as @a if score @s xp matches 230400.. run scoreboard players set @s levels 161
execute as @a if score @s xp matches 233289.. run scoreboard players set @s levels 162
execute as @a if score @s xp matches 236196.. run scoreboard players set @s levels 163
execute as @a if score @s xp matches 239121.. run scoreboard players set @s levels 164
execute as @a if score @s xp matches 242064.. run scoreboard players set @s levels 165
execute as @a if score @s xp matches 245025.. run scoreboard players set @s levels 166
execute as @a if score @s xp matches 248004.. run scoreboard players set @s levels 167
execute as @a if score @s xp matches 251001.. run scoreboard players set @s levels 168
execute as @a if score @s xp matches 254016.. run scoreboard players set @s levels 169
execute as @a if score @s xp matches 257049.. run scoreboard players set @s levels 170
execute as @a if score @s xp matches 260100.. run scoreboard players set @s levels 171
execute as @a if score @s xp matches 263169.. run scoreboard players set @s levels 172
execute as @a if score @s xp matches 266256.. run scoreboard players set @s levels 173
execute as @a if score @s xp matches 269361.. run scoreboard players set @s levels 174
execute as @a if score @s xp matches 272484.. run scoreboard players set @s levels 175
execute as @a if score @s xp matches 275625.. run scoreboard players set @s levels 176
execute as @a if score @s xp matches 278784.. run scoreboard players set @s levels 177
execute as @a if score @s xp matches 281961.. run scoreboard players set @s levels 178
execute as @a if score @s xp matches 285156.. run scoreboard players set @s levels 179
execute as @a if score @s xp matches 288369.. run scoreboard players set @s levels 180
execute as @a if score @s xp matches 291600.. run scoreboard players set @s levels 181
execute as @a if score @s xp matches 294849.. run scoreboard players set @s levels 182
execute as @a if score @s xp matches 298116.. run scoreboard players set @s levels 183
execute as @a if score @s xp matches 301401.. run scoreboard players set @s levels 184
execute as @a if score @s xp matches 304704.. run scoreboard players set @s levels 185
execute as @a if score @s xp matches 308025.. run scoreboard players set @s levels 186
execute as @a if score @s xp matches 311364.. run scoreboard players set @s levels 187
execute as @a if score @s xp matches 314721.. run scoreboard players set @s levels 188
execute as @a if score @s xp matches 318096.. run scoreboard players set @s levels 189
execute as @a if score @s xp matches 321489.. run scoreboard players set @s levels 190
execute as @a if score @s xp matches 324900.. run scoreboard players set @s levels 191
execute as @a if score @s xp matches 328329.. run scoreboard players set @s levels 192
execute as @a if score @s xp matches 331776.. run scoreboard players set @s levels 193
execute as @a if score @s xp matches 335241.. run scoreboard players set @s levels 194
execute as @a if score @s xp matches 338724.. run scoreboard players set @s levels 195
execute as @a if score @s xp matches 342225.. run scoreboard players set @s levels 196
execute as @a if score @s xp matches 345744.. run scoreboard players set @s levels 197
execute as @a if score @s xp matches 349281.. run scoreboard players set @s levels 198
execute as @a if score @s xp matches 352836.. run scoreboard players set @s levels 199
execute as @a if score @s xp matches 356409.. run scoreboard players set @s levels 200
execute as @a if score @s xp matches 360000.. run scoreboard players set @s levels 201
execute as @a if score @s xp matches 363609.. run scoreboard players set @s levels 202
execute as @a if score @s xp matches 367236.. run scoreboard players set @s levels 203
execute as @a if score @s xp matches 370881.. run scoreboard players set @s levels 204
execute as @a if score @s xp matches 374544.. run scoreboard players set @s levels 205
execute as @a if score @s xp matches 378225.. run scoreboard players set @s levels 206
execute as @a if score @s xp matches 381924.. run scoreboard players set @s levels 207
execute as @a if score @s xp matches 385641.. run scoreboard players set @s levels 208
execute as @a if score @s xp matches 389376.. run scoreboard players set @s levels 209
execute as @a if score @s xp matches 393129.. run scoreboard players set @s levels 210
execute as @a if score @s xp matches 396900.. run scoreboard players set @s levels 211
execute as @a if score @s xp matches 400689.. run scoreboard players set @s levels 212
execute as @a if score @s xp matches 404496.. run scoreboard players set @s levels 213
execute as @a if score @s xp matches 408321.. run scoreboard players set @s levels 214
execute as @a if score @s xp matches 412164.. run scoreboard players set @s levels 215
execute as @a if score @s xp matches 416025.. run scoreboard players set @s levels 216
execute as @a if score @s xp matches 419904.. run scoreboard players set @s levels 217
execute as @a if score @s xp matches 423801.. run scoreboard players set @s levels 218
execute as @a if score @s xp matches 427716.. run scoreboard players set @s levels 219
execute as @a if score @s xp matches 431649.. run scoreboard players set @s levels 220
execute as @a if score @s xp matches 435600.. run scoreboard players set @s levels 221
execute as @a if score @s xp matches 439569.. run scoreboard players set @s levels 222
execute as @a if score @s xp matches 443556.. run scoreboard players set @s levels 223
execute as @a if score @s xp matches 447561.. run scoreboard players set @s levels 224
execute as @a if score @s xp matches 451584.. run scoreboard players set @s levels 225
execute as @a if score @s xp matches 455625.. run scoreboard players set @s levels 226
execute as @a if score @s xp matches 459684.. run scoreboard players set @s levels 227
execute as @a if score @s xp matches 463761.. run scoreboard players set @s levels 228
execute as @a if score @s xp matches 467856.. run scoreboard players set @s levels 229
execute as @a if score @s xp matches 471969.. run scoreboard players set @s levels 230
execute as @a if score @s xp matches 476100.. run scoreboard players set @s levels 231
execute as @a if score @s xp matches 480249.. run scoreboard players set @s levels 232
execute as @a if score @s xp matches 484416.. run scoreboard players set @s levels 233
execute as @a if score @s xp matches 488601.. run scoreboard players set @s levels 234
execute as @a if score @s xp matches 492804.. run scoreboard players set @s levels 235
execute as @a if score @s xp matches 497025.. run scoreboard players set @s levels 236
execute as @a if score @s xp matches 501264.. run scoreboard players set @s levels 237
execute as @a if score @s xp matches 505521.. run scoreboard players set @s levels 238
execute as @a if score @s xp matches 509796.. run scoreboard players set @s levels 239
execute as @a if score @s xp matches 514089.. run scoreboard players set @s levels 240
execute as @a if score @s xp matches 518400.. run scoreboard players set @s levels 241
execute as @a if score @s xp matches 522729.. run scoreboard players set @s levels 242
execute as @a if score @s xp matches 527076.. run scoreboard players set @s levels 243
execute as @a if score @s xp matches 531441.. run scoreboard players set @s levels 244
execute as @a if score @s xp matches 535824.. run scoreboard players set @s levels 245
execute as @a if score @s xp matches 540225.. run scoreboard players set @s levels 246
execute as @a if score @s xp matches 544644.. run scoreboard players set @s levels 247
execute as @a if score @s xp matches 549081.. run scoreboard players set @s levels 248
execute as @a if score @s xp matches 553536.. run scoreboard players set @s levels 249
execute as @a if score @s xp matches 558009.. run scoreboard players set @s levels 250